name: Deploy
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node and install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Create ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ssh.strato.de >> ~/.ssh/known_hosts
      - name: Build application
        run: npm run build
        shell: bash
      - name: Deploy artifacts
        run: |
          scp -r ./out ${{secrets.STRATO_USERNAME}}@ssh.strato.de
